### ISSUE TITLE
IMU Magnetometer Disabled in Gazebo Simulation

### ISSUE THREAD

**Issue by Quest2GM** [jackal/jackal_simulator#17]
Hi,

I am trying to use the IMU controller for the Jackal in Gazebo (ie. without physical hardware) and I notice that when I do `rostopic list` (after running `roslaunch jackal_gazebo jackal_world.launch`) there are actually no magnetometer readings. Namely, I don't see a topic by the name `/imu/mag`; I only see `imu/data`. Is there a way to enable it? I am using Ubuntu 18.04 with ROS Melodic. Note that I do understand that the magnetometer readings may be inaccurate, as identified here, https://github.com/jackal/jackal_robot/issues/13, but I still want to be able to use it.

Another question I had was whether we would need to apply `imu_filter_madgwick` to the `imu/data` and `imu/mag` topics or whether these topics are already filtered through this algorithm. I saw somewhere that these published topics are already filtered but I just want to confirm it.

Thanks and I would appreciate a quick response,
Quest2GM

**Comment by civerachb-cpr** [comment]
Because the simulation is designed to replicate the physical robot, and the magnetometer is normally disabled on the real robots because of its proximity to the motors (which contain magnets) and other sources of EM noise, we did not add the magnetometer to the simulation.

To add a magnetometer to the simulation you can edit `jackal_description/urdf/jackal.gazebo` to add a block like the following:
```
  <gazebo>
    <!-- See http://wiki.ros.org/hector_gazebo_plugins#GazeboRosMagnetic -->
    <plugin name="mag_controller" filename="libhector_gazebo_ros_magnetic.so">
      <robotNamespace>/</robotNamespace>
      <updateRate>50.0</updateRate>
      <bodyName>imu_link</bodyName>
      <topicName>imu/mag</topicName>
      <magnitude>1.0</magnitude>
      <referenceHeading>90.0</referenceHeading>
      <declination>0.0</declination>
      <inclination>60.0</inclination>
      <offset>0.0 0.0 0.0</offset>
      <drift>0.005 0.005 0.005</drift>
      <gaussianNoise>0.025 0.025 0.025</gaussianNoise>
      <useMagneticFieldMsgs>false</useMagneticFieldMsgs>
    </plugin>
  </gazebo>
```

Alternatively, if you have installed the `jackal_description` package as a .deb and do not wish to edit files located in `/opt/ros` you can use the `JACKAL_URDF_EXTRAS` envar to modify the Jackal to add the magnetometer plugin by following these steps:

1. Create a URDF file somewhere in your workspace containing the following:
```
<xml version="1.0" ?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <gazebo>
    <!-- See http://wiki.ros.org/hector_gazebo_plugins#GazeboRosMagnetic -->
    <plugin name="mag_controller" filename="libhector_gazebo_ros_magnetic.so">
      <robotNamespace>/</robotNamespace>
      <updateRate>50.0</updateRate>
      <bodyName>imu_link</bodyName>
      <topicName>imu/mag</topicName>
      <magnitude>1.0</magnitude>
      <referenceHeading>90.0</referenceHeading>
      <declination>0.0</declination>
      <inclination>60.0</inclination>
      <offset>0.0 0.0 0.0</offset>
      <drift>0.005 0.005 0.005</drift>
      <gaussianNoise>0.025 0.025 0.025</gaussianNoise>
      <useMagneticFieldMsgs>false</useMagneticFieldMsgs>
    </plugin>
  </gazebo>
</robot>
```
2. Set the `JACKAL_URDF_EXTRAS` envar to point to this file before launching your simulation:
```
export JACKAL_URDF_EXTRAS=/path/to/the/file/created/above.urdf.xacro
roslaunch jackal_gazebo jackal_world.launch
```


Regarding the question of using a filter on the magnetometer data, I would recommend it.  Something like this would be a good starting point:
```
    <node pkg="imu_filter_madgwick" type="imu_filter_node" name="imu_filter_madgwick">
      <param name="~use_magnetic_field_msg" value="true" />
      <param name="~use_mag" value="true" />
      <param name="world_frame" value="enu" />
      <param name="publish_debug_topics" value="true" />
      <param name="~publish_tf" value="false" />
    </node>
```

Note that `imu_filter_madgwick` requires `MagneticField` messages, not `Vector3Stamped`, so in the Gazebo configuration above you would likely want to set `useMagneticFieldMsgs` to `true` instead of `false`.


Broadly-speaking, we do not recommend using the magnetometer on the physical Jackal for any sort of serious localization work; the magnetometer is part of the IMU chip built into the Jackal's MCU.  This is mounted to the inside rear wall of the robot, very close to one of the motors and several power cables.  This, combined with the Jackal's metal construction, can make the magnetometer data unusably noisy.  You're welcome to experiment and try to use it, but you should be aware of this limitation if you do move your work out of the simulation and onto the physical robot.

**Comment by Quest2GM** [comment]
Thanks @civerachb-cpr, this is very clear.

As a follow up, what if we bought an external IMU and attached it to the Jackal? Where is the best place to put the IMU on the physical Jackal to mitigate the effects of power cables and metal construction on the magnetometer (or does putting it anywhere still screw it up)? Moreover, the above steps for simulating the IMU in Gazebo would still apply for an externally bought IMU, correct (if not, how would it change)?

**Comment by civerachb-cpr** [comment]
Broadly-speaking, placing the IMU on the outside of the Jackal's chassis will likely have the best performance.  You can pass the USB cable through the hole in the rear of the Jackal's lid to reach the PC and mount it somewhere to the top of the robot on the outside, away from motors, antennas, etc...  I can't guarantee this will work well, but it should work better than placing the IMU inside the computer bay.

For adding an external IMU to the physical Jackal, the process would be something like this:

1. Mount the IMU.  You should measure the XYZ position and note its orientation.
2. Install a ROS driver for your IMU.  This will depend on the manufacturer.
3. Create a URDF "stub" file containing the link of your new IMU:
```
<?xml version="1.0" ?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <!-- A link for the external IMU -->
  <link name="external_imu_link" />
  <joint name="external_imu_joint" type="fixed">
    <parent link="base_link" />  <!-- can be any link on the robot; origin is the measurement relative to this link -->
    <child link="external_imu_link" />
    <origin xyz="0 0 0" rpy="0 0 0" />  <!-- replace XYZ + RPY with measurements from step 1 -->
  </joint>
</robot>
```
4. On the robot, edit `/etc/ros/setup.bash` to set the `JACKAL_URDF_EXTRAS` envar to point to this URDF file:
```
export JACKAL_URDF_EXTRAS=/path/to/the/file/from/step3.urdf.xacro
```
5. Copy the IMU's launch file into `/etc/ros/$ROS_DISTRO/ros.d`. Edit the driver as necessary to ensure that it publishes data on a different topic; the Jackal's internal IMU + Magnetometer will still publish on `/imu/data` and `/imu/mag`.  Your external IMU should use unique topics.  You'll also need to make sure the new IMU driver uses the `external_imu_link` as its frame to make sure the data can be `tf`'d appropriately.
6. (Optional, but recommended) Configure EKF to use the new IMU instead of the Jackal's internal one.  The internal IMU is sufficient for most simple tasks, but most external IMUs will be higher-precision, and will provide better input to the EKF node. To do this you'll need to create a configuration file:
```
ekf_localization:
    imu1: /external/imu/topic     # replace this with the topic your IMU publishes on
    imu1_config: [false, false, false,
        true, true, true,
        false, false, false,
        true, true, true,
        false, false, false]
    imu1_differential: false
```
and set the `JACKAL_CONTROL_EXTRAS` and `JACKAL_CONTROL_EXTRAS_PATH` envars in `/etc/ros/setup.bash`:
```
export JACKAL_CONTROL_EXTRAS=1
export JACKAL_CONTROL_EXTRAS_PATH=/path/to/config/file.yaml
```
7. (Optional) You can add IMU filters if desired using the same process I described for the simulation. Note that you may need to create a simple Python node to convert `Vector3Stamped` messages into `MagneticField` messages used by the `imu_filter_madgwick` if the driver for your IMU publishes magnetometer data using the new message format.

**Comment by Quest2GM** [comment]
Thank you! This is really helpful!
