### ISSUE TITLE
ROS Jade / Gazebo 5 support

### ISSUE THREAD

**Issue by davetcoleman** [jackal/jackal_simulator#6]
Any plans to migrate jackal to Jade and the many new features of Gazebo?

**Comment by mikepurvis** [comment]
I played with it briefly, and encountered a [very weird bug related to the built-in velocity controller](http://answers.gazebosim.org/question/8994/jackal-simulator-flipping-and-flying-in-gazebo-51/). I posted a workaround on my own question, but I haven't bothered committing it here, in part because I still don't really understand the underlying cause of the problem.

All in all, there hasn't been demand, and I had trouble getting much support from OSRF for Gazebo migration related issues. That said, if there are specific features of the new Gazebo you'd like to see supported and/or you have the energy to contribute changes or review, I'd be glad to collaborate on it.

**Comment by dniewinski** [comment]
Jackal Gazebo will be updated for Kinetic shortly, which will carry all the benefits of Jade.  If this solves your issue, please let me know and I can close the issue.  If not, what changes were you looking for in Jade?

**Comment by dniewinski** [comment]
Despite many delays, we have finally finished and released support for Kinetic! Many of the packages should be available through http://packages.ros.org or from http://packages.clearpathrobotics.com and will encompass any of the improvements included in Jade
